qube_version: '2.6.1 # <<QUBE_NO_BUMP>>'
full_name: Andreas Friedrich
email: andreas.friedrich@qbic.uni-tuebingen.de
project_name: Experimental Design Library
project_short_description: Parsers, writers for experimental design formats etc.
version: 0.20.1
domain: lib
language: java
project_slug: Experimental_Design_Library
project_slug_no_hyphen: Experimental_Design_Library
template_version: '1.0.5 # <<QUBE_NO_BUMP>>'
template_handle: lib-java
github_username: wow-such-code
creator_github_username: wow-such-code
is_github_repo: false
is_repo_private: false
is_github_orga: false
copyright_holder: QBiC
license: MIT
